### ISSUE TITLE
Can't save Gitlab Token in redmine 3.2.0

### ISSUE THREAD

**Issue by dreampet** [sazor/redmine_gitlab_integration#8]
In Redmine “My account” page，It can't not save the gitlab token,have a error msg:
 "GitLab Token isn`t valid" 

and the error info in Production.log:

ActionController::RoutingError (No route matches [GET] "/plugin_assets/redmine_gitlab_integration/stylesheets/flaticon.css"):
  actionpack (4.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
  actionpack (4.2.5) lib/action_dispatch/middleware/show_exceptions.rb:30:in`call'
  railties (4.2.5) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.5) lib/rails/rack/logger.rb:20:in`block in call'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:26:in`tagged'
  activesupport (4.2.5) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.5) lib/rails/rack/logger.rb:20:in`call'
  actionpack (4.2.5) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.4) lib/rack/methodoverride.rb:22:in`call'
  rack (1.6.4) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.5) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in`call'
  actionpack (4.2.5) lib/action_dispatch/middleware/static.rb:116:in `call'
  rack (1.6.4) lib/rack/sendfile.rb:113:in`call'
  railties (4.2.5) lib/rails/engine.rb:518:in `call'
  railties (4.2.5) lib/rails/application.rb:165:in`call'
  railties (4.2.5) lib/rails/railtie.rb:194:in `public_send'
  railties (4.2.5) lib/rails/railtie.rb:194:in`method_missing'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:152:in`accept_and_process_next_request'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in`block (3 levels) in start_threads'
  /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'

the redmine info:
Environment:
  Redmine version             3.2.0.stable
  Ruby version                   2.1.7-p400 (2015-08-18) [x86_64-linux]
  Rails version                    4.2.5
  Environment                     production
  Database adapter            Mysql2
SCM:
  Cvs                            1.12.13
  Git                              1.9.1
  Filesystem  
Redmine plugins:
  a_common_libs                  2.0.0
  advanced_roadmap_v2            2.4.2
  clipboard_image_paste          1.10
  file_servers                   3.0.2
  redmine_banner                 0.1.1
  redmine_checklists             3.1.3
  redmine_code_review            0.7.0
  redmine_gitlab_integration     0.4.0
  redmine_remote_revision_url    0.3.0
  redmine_revision_branches      0.3.0
  redmine_work_time              0.3.1

**Comment by texnoid** [comment]
Мужик! Спасай нас, всё пропало, ошибка у многих такая.
